version: "3.9"

services:
  drycontainer_simulator:
    image: drycontainer
    build:
      context: ./dry_container_simulator
      dockerfile: Dockerfile.telegraf
    network_mode: host
    volumes:
      - ../../config:/app/config
      - ./app.log:/app/app.log

  route_simulator:
    image: route
    build:
      context: ./route_simulator
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ../../config:/src/config
      - ../../config/status/voyage_text:/src/voyage_text
      - ./app.log:/src/app.log

  opcua_server:
    image: opcua
    build:
      context: ./opcua_server
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ../../config:/src/config
      - ./app.log:/src/app.log

  reefer_simulator:
    image: reefer
    build:
      context: ./reefer_container_simulator
      dockerfile: Dockerfile.telegraf
    network_mode: host
    volumes:
      - ../../config:/app/config
      - ./app.log:/app/app.log

  analytics:
    image: analytics
    build:
      context: ./analytics
      dockerfile: Dockerfile.telegraf
    network_mode: host
    volumes:
      - ../../config:/app/config
      - ./app.log:/app/app.log

  safety:
    image: safety
    build:
      context: ./safety
      dockerfile: Dockerfile.telegraf
    network_mode: host
    volumes:
      - ../../config:/app/config
      - ./safety/src:/app
      - ./app.log:/app/app.log

  influxdb:
    image: influxdb:1.7.10
    ports:
    - "8086:8086"
