apiVersion: v1
kind: Service
metadata:
  name: vss-service
  namespace: videosearch
  labels:
    app: vss-vss-deployment
    app.kubernetes.io/instance: vss-blueprint
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vss
    app.kubernetes.io/version: 2.1.0
    generated_with: helm_builder
    hb_version: 1.0.0
    helm.sh/chart: vss-2.1.0
    microservice_version: 2.1.0
    msb_version: 2.5.0
annotations:
  meta.helm.sh/release-name: vss-blueprint
  meta.helm.sh/release-namespace: videosearch
spec:
  type: NodePort
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  clusterIP: 10.101.156.22
  ports:
    - name: http-api
      port: 8000
      targetPort: 8000
      nodePort: 31394
    - name: webui
      port: 9000
      targetPort: 9000
      nodePort: 31107
  selector:
    app: vss-vss-deployment
