# Created by Scalers AI for Dell Inc.

version: "3.9"

services:
  # sensor data analytics service
  sensor-analytics:
    image: analytics
    build:
      context: ./analytics
      dockerfile: Dockerfile
    volumes:
      - ../config:/config
    network_mode: host
    depends_on:
      - influxdb

  # influxDB service
  influxdb:
    image: influxdb:1.7.10
    restart: on-failure:10
    ports:
      - 8086:8086
