# endpoint configuration
opcua_endpoint_url: "opc.tcp://localhost:4840"

# simulator config
namespaces:
  container_simulators:
    interval: 1 # in seconds
    devices:
      dry_container: # node object
        replicas: 250
        sensor_nodes: # objects
          TH_sensor:
            variables:
              - Temperature
              - Humidity
      reefer_container: # node object
        replicas: 300
        sensor_nodes: # objects
          TH_sensor:
            variables:
              - Temperature
              - Humidity
  location_simulators:
    interval: 1 # in seconds
    devices:
      location: # node object
        replicas: 1
        sensor_nodes: # objects
          TH_sensor:
            variables:
              - Longitude
              - Latitude
              - Temperature
              - Humidity