---
apiVersion: batch/v1
kind: Job
metadata:
  name: vllm-benchmark
spec:
  template:
    spec:
      initContainers:
      # Replace dockerregistryIP with docker private registry IP address
      - name: init-vllm-benchmark
        image: dockerregistryIP:5500/vllm_benchmark:latest
        workingDir: /root
        command:
        - bash
        args:
        - -c
        - 'sleep 200'
        env:
        - name: VLLM_URL
          value: "http://vllm:8000" # Port exposed by the Service
        # Change model as needed  
        - name: MODEL
          value: meta-llama/Meta-Llama-3-8B
        volumeMounts:
        - name: data
          mountPath: /root
        - name: config
          mountPath: /root/config
 
      containers:
      # Replace dockerregistryIP with docker private registry IP address
      - name: run-generation
        image: dockerregistryIP:5500/vllm_benchmark:latest
        workingDir: /root
        command:
          - bash
        args:
          - -c
          - 'config/benchmark.sh'
       
        env:
        - name: MODEL
          value: meta-llama/Meta-Llama-3-8B
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: hf-token
        - name: HUGGINGFACE_API_KEY
          value: EMPTY
        - name: OPENAI_API_BASE
          value: "http://vllm:8000/v1"
        - name: OPENAI_API_KEY
          value: EMPTY
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: huggingface-cache
          mountPath: /home/root/.cache/huggingface
        - name: data
          mountPath: /root
        - name: config
          mountPath: /root/config
        - name: dshm
          mountPath: /dev/shm
        imagePullPolicy: Always
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: vllm
            defaultMode: 0500
        - name: data
          hostPath:
            path: /scratch-1/vllm/
            type: Directory
        - name: dshm
          emptyDir:
            medium: Memory
        # Provide the path to the local copy of models if needed
        - name: huggingface-cache
          hostPath:
            path: /path/to/.cache/huggingface
            type: Directory
