
# Stream details
voyage_details:
  voyage_number: VS123456
  vessel_name: MV Ocean Explorer
  captain: Captain John Smith
  departure_port: Shanghai
  arrival_port: Lisbon
  departure_date: January 1, 2024
  arrival_date_est: February 5, 2024
  total_voyage_duration_days: 36

cargo_info:
  total_containers: 550
  reefer_containers: 300
  container_type: 40ft
  reefer_set_temp: 2

simulator_templates:
  reefer_template: /app/config/reefer.csv
  dry_container_template: /app/config/drycontainer.csv
  shipping_route: /app/config/route.csv
  route_sim_time: 100

gpu_config:
  video_pipeline_gpus: [1]
  llm_gpus: [0]

# Stream details
rtsp_streams:
  CAM-TI1:
      url: rtsp://localhost:8554/trans1.mp4
      broker: localhost
      zone: /pipeline/zone.json
      visualize:  true

  CAM-TI2:
      url: rtsp://localhost:8554/trans2.mp4
      broker: localhost
      zone: /pipeline/zone2.json
      visualize:  true

  CAM-TI3:
      url: rtsp://localhost:8554/trans3.mp4
      broker: localhost
      zone: /pipeline/zone3.json
      visualize:  true

  CAM-TI4:
      url: rtsp://localhost:8554/trans3.mp4
      broker: localhost
      zone: /pipeline/zone3.json
      visualize:  true
