# Created by Scalers AI for Dell Inc.

version: "3.9"

services:

  # OPC UA Server service
  opcua-server:
    image: opcua-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4840:4840
    volumes:
      - ../config:/config
