# Created by Scalers AI for Dell Inc.

version: "3.9"

services:
  rtsp_server:
    image: bluenviron/mediamtx:1.5.1
    ports:
      - 8554:8554
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 8890:8890/udp
      - 8189:8189/udp
    environment:
      - MTX_PROTOCOLS=tcp

  video_publisher:
      image: publisher
      build:
        context: ./video_simulator
        dockerfile: Dockerfile
      depends_on:
        - rtsp_server
      volumes:
        - ./sample_videos:/media
