# Created by scalers.ai for Dell

# Chatbot container deployment
version: "3.9"
services:
  chatbot:
    image: chatbot
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    volumes:
    - ./src:/code
    - $TRAINING_DIR:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
