# Product information
product_name: "Dell PowerEdge R7615"
CPU_name: "AMD EPYC 9354P Processor"
num_sockets: "1"
num_cores: "32"

# Stream details
rtsp_streams:
  CAM-TI1:
      url: /src/sku1.mp4
      broker: localhost
      items_config: /src/config/TI1.json
      udp_port: 1234
      visualize:  true
  CAM-TI2:
      url: /src/sku2.mp4
      broker: localhost
      items_config: /src/config/TI2.json
      udp_port: 1235
      visualize:  true
