# Created by Scalers AI for Dell Inc.

# simulator config
namespaces:
  hvac:
    interval: 1 # in seconds
    devices:
      Compressor_A76_STN2_Z1: # node object
        replicas: 1
        rate_change: [-10.0, 10.0] # this is ignored if replica is 1
        value_range: [-1, 1] # limit max and min the values here
        sensor_nodes: # objects
          tachometer:
            variables:
              - t1
          underhang_accelerometer:
            variables: # variable/objects
              - a1
              - a2
              - a3
          overhang_accelerometer:
            variables: # variable/objects
              - a4
              - a5
              - a6
          sound:
            variables:
              - s1
        base_path: /simulator_data
        simulator_files:
          normal:
            file_name: normal.csv
            row_count: 10
      Compressor_A76_STN2_Z2: # node object
        replicas: 1
        rate_change: [-10.0, 10.0] # this is ignored if replica is 1
        value_range: [-1, 1] # limit max and min the values here
        sensor_nodes: # objects
          tachometer:
            variables:
              - t1
          underhang_accelerometer:
            variables: # variable/objects
              - a1
              - a2
              - a3
          overhang_accelerometer:
            variables: # variable/objects
              - a4
              - a5
              - a6
          sound:
            variables:
              - s1
        base_path: /simulator_data
        simulator_files:
          normal:
            file_name: normal.csv
            row_count: 10
      Compressor_A76_STN2_Z3: # node object
        replicas: 1
        rate_change: [-10.0, 10.0] # this is ignored if replica is 1
        value_range: [-1, 1] # limit max and min the values here
        sensor_nodes: # objects
          tachometer:
            variables:
              - t1
          underhang_accelerometer:
            variables: # variable/objects
              - a1
              - a2
              - a3
          overhang_accelerometer:
            variables: # variable/objects
              - a4
              - a5
              - a6
          sound:
            variables:
              - s1
        base_path: /simulator_data
        simulator_files:
          normal:
            file_name: normal.csv
            row_count: 10
          cage_fault:
            file_name: cage_fault.csv
            row_count: 1
      Compressor_A76_STN4_Z4: # node object
        replicas: 1
        rate_change: [-10.0, 10.0] # this is ignored if replica is 1
        value_range: [-1, 1] # limit max and min the values here
        sensor_nodes: # objects
          tachometer:
            variables:
              - t1
          underhang_accelerometer:
            variables: # variable/objects
              - a1
              - a2
              - a3
          overhang_accelerometer:
            variables: # variable/objects
              - a4
              - a5
              - a6
          sound:
            variables:
              - s1
        base_path: /simulator_data
        simulator_files:
          normal:
            file_name: normal.csv
            row_count: 10
          cage_fault:
            file_name: cage_fault.csv
            row_count: 3
          normal:
            file_name: normal.csv
            row_count: 5
