version: "3.9"

services:
  receiver:
    container_name: receiver
    build:
      context: ./receive
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ../config:/src/config
      - ./app.log:/src/app.log
    restart: always

  visualization:
    image: visualization
    build:
      context: ./visualization
      dockerfile: Dockerfile.visualization
    container_name: visualization
    network_mode: host
    volumes:
      - ../config/config.yaml:/example-webrtc-applications/gstreamer-send/pipeline_config.yml
    environment:
    - SERVER_IP=$SERVER_IP

  signaling:
    image: signaling
    build:
      context: ./webrtc_signaling
      dockerfile: Dockerfile.signaling
    network_mode: host
    volumes:
      - ./webrtc_signaling/src:/src

  telegraf:
    image: telegraf
    build:
      context: ./telegraf
      dockerfile: Dockerfile.telegraf
    network_mode: host
    volumes:
      - ../config/config.yaml:/app/config.yaml

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    volumes:
      - ../config:/src/config
    network_mode: host
    environment:
    - SERVER_IP=$SERVER_IP

  influxdb:
    image: influxdb:1.7.10
    ports:
    - "8086:8086"
